### ISSUE TITLE
Problem using Promises (Bluebird)

### ISSUE THREAD

**Issue by larsenjh** [Jeff-Lewis/cls-hooked#6]
I have noticed that while using Promises (bluebird) that sometimes I loose the context and cannot get my stored variables. I also noticed that `async-listener` addressed something like this by adding its own monkey patch to native promises. Have you experienced any issues using this library with promises?

**Comment by Jeff-Lewis** [comment]
Quick answer: yes, you will loose context with an unpatched bluebird. Take a look at 'cls-bluebird' https://github.com/TimBeyer/cls-bluebird.

**Comment by larsenjh** [comment]
Ah! Thank you for that.

**Comment by stuurman** [comment]
@Jeff-Lewis So 'cls-bluebird' does patch 'cls-hooked' reliably (since 'cls-bluebird' mentions it is made for [continuation-local-storage](https://www.npmjs.com/package/continuation-local-storage))?

My context is that I want to keep using BlueBird in my code calling [Sequelize](https://sequelize.org/docs/v6/other-topics/upgrade/#cls), who in their upgrade from V5 to V6 started using your library 'cls-hooked' instead of 'continuation-local-storage'
